tubemap = {"Aldgate" : ["Liverpool Street - Circle","Tower Hill - Circle"],
"Aldgate East" : ["Tower Hill - District","Liverpool Street - Hammersmith & City"],
"Angel" : ["King's Cross St. Pancras - Northern","Old Street - Northern"],
"Baker Street" : ["Marylebone - Bakerloo","Regent's Park - Bakerloo","Edgware Road - Circle","Great Portland Street - Circle","Bond Street - Jubilee"],
"Bank" : ["Liverpool Street - Central","St. Paul's - Central","London Bridge - Northern","Moorgate - Northern","Waterloo - Waterloo & City"],
"Barbican" : ["Farringdon - Circle","Moorgate - Circle"],
"Bayswater" : ["Paddington - Circle"],
"Blackfriars" : ["Mansion House - Circle","Temple - Circle"],
"Bond Street" : ["Marble Arch - Central","Oxford Circus - Central","Green Park - Jubilee","Baker Street - Jubilee"],
"Borough" : ["London Bridge - Northern"],
"Cannon Street" : ["Mansion House - Circle","Monument - Circle"],
"Chancery Lane" : ["Holborn - Central","St. Paul's - Central"],
"Charing Cross" : ["Embankment - Bakerloo","Picadilly Circus - Bakerloo","Leicester Square - Northern"],
"Covent Garden" : ["Holborn - Picadilly","Leicester Square - Picadilly"],
"Edgware Road" : ["Marylebone - Bakerloo","Paddington - Circle", "Baker Street - Circle"],
"Embankment" : ["Waterloo - Bakerloo","Temple - Circle","Westminster - Circle","Charing Cross - Bakerloo"],
"Euston" : ["King's Cross St. Pancras - Victoria","Warren Street - Victoria"],
"Euston Square" : ["Great Portland Street - Circle","King's Cross St. Pancras - Circle"],
"Farringdon" : ["King's Cross St. Pancras - Circle","Barbican - Circle"],
"Gloucester Road" : ["High Street Kensington - Circle","South Kensington - Circle"],
"Goodge Street" : ["Tottenham Court Road - Northern","Warren Street - Northern"],
"Great Portland Street" : ["Baker Street - Circle","Euston Square - Circle"],
"Green Park" : ["Westminster - Jubilee","Hyde Park Corner - Picadilly","Picadilly Circus - Picadilly","Oxford Circus - Victoria","Victoria - Victoria","Bond Street - Jubilee"],
"High Street Kensington" : ["Gloucester Road - Circle"],
"Holborn" : ["Tottenham Court Road - Central","Russell Square - Picadilly","Chancery Lane - Central","Covent Garden - Picadilly"],
"Hyde Park Corner" : ["Knightsbridge - Picadilly","Green Park - Picadilly"],
"King's Cross St. Pancras" : ["Russell Square - Picadilly","Euston Square - Circle","Farringdon - Circle","Angel - Northern","Euston - Northern"],
"Knightsbridge" : ["South Kensington - Picadilly","Hyde Park Corner - Picadilly"],
"Lambeth North" : ["Waterloo - Bakerloo"],
"Lancaster Gate" : ["Marble Arch - Central","Queensway - Central"],
"Leicester Square" : ["Tottenham Court Road - Northern","Picadilly Circus - Picadilly","Charing Cross - Northern","Covent Garden - Picadilly"],
"Liverpool Street" : ["Moorgate - Circle","Bank - Central","Aldgate - Circle","Aldgate East - Hammersmith & City"],
"London Bridge" : ["Southwark - Jubilee","Bank - Northern","Borough - Northern"],
"Mansion House" : ["Blackfriars - Circle","Cannon Street - Circle"],
"Marble Arch" : ["Bond Street - Central","Lancaster Gate - Central"],
"Marylebone" : ["Baker Street - Bakerloo","Edgware Road - Bakerloo"],
"Monument" : ["Tower Hill - Circle","Cannon Street - Circle"],
"Moorgate" : ["Old Street - Northern","Barbican - Circle","Liverpool Street - Circle","Bank - Northern"],
"Old Street" : ["Angel - Northern","Moorgate - Northern"],
"Oxford Circus" : ["Picadilly Circus - Bakerloo","Regent's Park - Bakerloo","Tottenham Court Road - Central","Warren Street - Victoria","Bond Street - Central","Green Park - Victoria"],
"Paddington" : ["Edgware Road - Circle","Bayswater - Circle"],
"Picadilly Circus" : ["Charing Cross - Bakerloo","Oxford Circus - Bakerloo","Green Park - Picadilly","Leicester Square - Picadilly"],
"Pimlico" : ["Victoria - Victoria"],
"Queensway" : ["Lancaster Gate - Central"],
"Regent's Park" : ["Baker Street - Bakerloo","Oxford Circus - Bakerloo"],
"Russell Square" : ["Holborn - Picadilly","King's Cross St. Pancras - Picadilly"],
"Sloane Square" : ["South Kensington - Circle","Victoria - Circle"],
"South Kensington" : ["Gloucester Road - Circle","Sloane Square - Circle","Knightsbridge - Picadilly"],
"Southwark" : ["Waterloo - Jubilee","London Bridge - Jubilee"],
"St. James's Park" : ["Victoria - Circle","Westminster - Circle"],
"St. Paul's" : ["Bank - Central","Chancery Lane - Central"],
"Temple" : ["Blackfriars - Circle","Embankment - Circle"],
"Tottenham Court Road" : ["Holborn - Central","Oxford Circus - Central","Goodge Street - Northern","Leicester Square - Northern"],
"Tower Hill" : ["Aldgate - Circle","Monument - Circle","Aldgate East - District"],
"Victoria" : ["Sloane Square - Circle","St. James's Park - Circle","Green Park - Victoria","Pimlico - Victoria"],
"Warren Street" : ["Euston - Victoria","Goodge Street - Northern","Oxford Circus - Victoria"],
"Waterloo" : ["Westminster - Jubilee","Embankment - Bakerloo","Lambeth North - Bakerloo","Southwark - Jubilee","Bank - Waterloo & City"],
"Westminster" : ["Embankment - Circle","St. James's Park - Circle","Green Park - Jubilee","Waterloo - Jubilee"]}
